Picked up JAVA_TOOL_OPTIONS: -Xmx16g
Picked up _JAVA_OPTIONS: -Xmx18g -Xss2m
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH does not contain the current folder '.'. Its value is '/users/stud09/martinsd/local/jdk1.8.0_191/lib/lserver/:'.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
Picked up JAVA_TOOL_OPTIONS: -Xmx16g
Picked up _JAVA_OPTIONS: -Xmx18g -Xss2m
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH does not contain the current folder '.'. Its value is '/users/stud09/martinsd/local/jdk1.8.0_191/lib/lserver/:'.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
java.lang.NullPointerException
org.esa.snap.core.gpf.OperatorException: java.lang.NullPointerException
	at org.esa.snap.engine_utilities.gpf.OperatorUtils.catchOperatorException(OperatorUtils.java:432)
	at org.esa.s1tbx.calibration.gpf.Sentinel1RemoveThermalNoiseOp.initialize(Sentinel1RemoveThermalNoiseOp.java:140)
	at org.esa.snap.core.gpf.internal.OperatorContext.initializeOperator(OperatorContext.java:486)
	at org.esa.snap.core.gpf.internal.OperatorContext.getTargetProduct(OperatorContext.java:273)
	at org.esa.snap.core.gpf.Operator.getTargetProduct(Operator.java:387)
	at org.esa.snap.core.gpf.main.CommandLineTool.runOperator(CommandLineTool.java:306)
	at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:284)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:188)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:121)
	at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54)
	at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.esa.snap.runtime.Launcher.lambda$run$14(Launcher.java:55)
	at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
	at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
	at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)

Error: java.lang.NullPointerException
/users/stud09/martinsd/proj/buhayra/sar2watermask/sar.py:277: RuntimeWarning: All-NaN slice encountered
  if (np.nanmax(r_db)< np.iinfo(np.int16).max) and (np.nanmin(r_db) > (np.iinfo(np.int16).min+1)):
/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/site-packages/rasterio/__init__.py:226: NotGeoreferencedWarning: Dataset has no geotransform set. The identity matrix may be returned.
  **kwargs)
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 199, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 194, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: '/mnt/scratch/martinsd/s1a_scenes/out/S1A_IW_GRDH_1SDV_20180329T081747_20180329T081812_021227_024813_2184_25153_CalSfCorr_big.tif' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/users/stud09/martinsd/proj/buhayra/__main__.py", line 101, in <module>
    main()
  File "/users/stud09/martinsd/proj/buhayra/__main__.py", line 48, in main
    sar.sar2sigma(f)
  File "/users/stud09/martinsd/proj/buhayra/sar2watermask/sar.py", line 342, in sar2sigma
    compress_tiff(sarOut+"/"+fname+'_big'+'.tif')
  File "/users/stud09/martinsd/proj/buhayra/sar2watermask/sar.py", line 271, in compress_tiff
    with rasterio.open(path,'r') as ds:
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/site-packages/rasterio/env.py", line 398, in wrapper
    return f(*args, **kwds)
  File "/users/stud09/martinsd/local/miniconda2/envs/buhayra/lib/python3.6/site-packages/rasterio/__init__.py", line 217, in open
    s = DatasetReader(path, driver=driver, **kwargs)
  File "rasterio/_base.pyx", line 201, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: '/mnt/scratch/martinsd/s1a_scenes/out/S1A_IW_GRDH_1SDV_20180329T081747_20180329T081812_021227_024813_2184_25153_CalSfCorr_big.tif' not recognized as a supported file format.
